version: '3.9'

services:
  postgresql:
    image: postgres:14
    container_name: db
    environment:
      - POSTGRES_DB=scrapper
      - POSTGRES_USER=polina
      - POSTGRES_PASSWORD=123
    restart: always
    expose:
      - 5432
    networks:
      - backend
    ports:
      - "5433:5432"
    volumes:
      - ./migrationspg-data:/var/lib/postgresql/data

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=polina
      - --password=123
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend:

volumes:
  pg-data: