version: '3.9'

services:
  postgresql:
    image: postgres:14
    environment:
      POSTGRES_USER: polina
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: scrapper
    volumes:
      - scrapper_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - postgresql
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=polina
      - --password=123
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

networks:
  backend:

volumes:
  scrapper_data:
