global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'scrapper'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'scrapper:8081' ]

  - job_name: 'bot'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'bot:8001' ]
