spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/scrapper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: rabbitmq
    port: 5672

  application:
    name: scrapper

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

  liquibase:
    enabled: false

management:

  info:
    env:
      enabled: true

  server:
    port: 8081

  endpoints:
    web:
      base-path: '/'
      path-mapping:
        prometheus: 'metrics'
      exposure:
        include: [ 'info', 'health', 'prometheus' ]
    enabled-by-default: true

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

app:
  scheduler:
    interval: 15S
  link-update-age: 15S
  database-access-type: jdbc
  use-queue: true
  rabbitmq:
    exchange: link-update.exchange
    queue: new-link-update.queue
    key: new  # new updates go to new-... queue
    dlx: link-update.dlx

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

github-client:
  base-url: https://api.github.com
  api-key: ${GITHUB_API_KEY}
  api-version: 2022-11-28

stackoverflow-client:
  base-url: https://api.stackexchange.com/2.3
  api-key: ${STACKOVERFLOW_API_KEY}
