name: Bot module

on:
  push:
    paths:
      - 'bot/**'
      - '.github/workflows/bot.yml'


env:
  REGISTRY: ghcr.io
  USERNAME: emiask

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Maven package
        run: mvn package -pl bot -am

      - name: Build  image
        run: docker build bot/ -t $REGISTRY/$USERNAME/bot:latest

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: docker push $REGISTRY/$USERNAME/bot:latest

  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Check code
        run: mvn -pl bot checkstyle:check
